
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmV6prBLHWcFDXhOqSqYsOCrwjf9Ty_vQ',
    appId: '1:573811660928:web:572c04778d0231a6ce6e65',
    messagingSenderId: '573811660928',
    projectId: 'music2-fb3b8',
    authDomain: 'music2-fb3b8.firebaseapp.com',
    storageBucket: 'music2-fb3b8.appspot.com',
    measurementId: 'G-E3XTY45QVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHx9CNeBjr7ZfXvW9IR8R7ZQ12rbntmo',
    appId: '1:573811660928:android:4b467420156cedb3ce6e65',
    messagingSenderId: '573811660928',
    projectId: 'music2-fb3b8',
    storageBucket: 'music2-fb3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qgIQ8vrFpkLnWWLhDH-D0gEEFnnc09I',
    appId: '1:573811660928:ios:ff70670fddbe98bace6e65',
    messagingSenderId: '573811660928',
    projectId: 'music2-fb3b8',
    storageBucket: 'music2-fb3b8.appspot.com',
    iosClientId: '573811660928-kbf9tdaojq8k6l4tq0cgnop1edf5d7fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.music2',
  );
}
